// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/alphabeter/Go-000/demo/api"
	"github.com/alphabeter/Go-000/demo/repository"
	"github.com/alphabeter/Go-000/demo/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUserAPI(db *gorm.DB) api.UserAPI {
	userRepository := repository.ProvideUserRepository(db)
	userService := service.ProvideUserService(userRepository)
	userAPI := api.ProvideUserAPI(userService)
	return userAPI
}
